% Function to generate coupled tensors
% Coupled in 'P' modes with data generated by using gaussian distribution

function [Tensor_A,Tensor_B]= Generate_Coupled_Tensors(Dimension_A,Rank_A,Dimension_B,Rank_B,Coupled_Modes_AB,MU_AB,Sigma_AB)

%Input
% Dimension_A           : Dimensions of Tensor A (order of each
%                         fiber)supplied as a row vector
% Rank_A                : Rank of Tensor A 
% Dimension_B           : Dimensions of Tensor B (order of each fiber)
%                         supplied as a row vector
% Rank_B                : Rank of Tensor B
% Coupled_Modes_AB      : Array of order 2*P, each column specifies the mode
%                         in Tensor A coupled with which mode in Tensor B
% MU_AB                 : Mean of gaussian distributiuon in each Coupled Mode
% Sigma_AB              : Variance of Gaussian Distribution in each Coupled mode 
% Noise_level           : Some noise addede to the coupled modes of tensors
% 
% Output
% Tensor_A              : Tensor 'A' of Mode 'N' having 'P' modes coupled with
%                         Tensor B
% Tensor_B              : Tensor 'B' of Mode 'M' having 'P' modes coupled with
%                         Tensor A
% 
% Author                : Sunny Verma (sunnyverma.iitd@gmail.com)
% Last_Update           : 19/05/2016

% % 


Size_A=size(Dimension_A,2);
Size_B=size(Dimension_B,2);
No_of_Coupled_Modes=size(Coupled_Modes_AB,2);
Factor_A=cell(Size_A,1);
Factor_B=cell(Size_B,1);

for i=1:Size_A
    Factor_A{i,1}=rand(Dimension_A(1,i),Rank_A);
end

for i=1:Size_B
    Factor_B{i,1}=rand(Dimension_B(1,i),Rank_B);
end

Columns_AB=Rank_A+Rank_B;
 
for i=1:No_of_Coupled_Modes
    Rows_Coupled_AB=Dimension_A(1,Coupled_Modes_AB(1,i))+Dimension_B(1,Coupled_Modes_AB(2,i));
    Coupled_Data=normrnd(MU_AB(1,i),Sigma_AB(1,i),Rows_Coupled_AB,Columns_AB);
    Factor_A{Coupled_Modes_AB(1,i),1}=Coupled_Data(1:Dimension_A(1,Coupled_Modes_AB(1,i)),1:Rank_A);
    Factor_B{Coupled_Modes_AB(2,i),1}=Coupled_Data(Dimension_A(1,Coupled_Modes_AB(1,i))+1:end,Rank_A+1:Rank_A+Rank_B);
end

Data_A=sum(khatrirao(Factor_A,'r'),2);
Tensor_A=tensor(Data_A,Dimension_A);


Data_B=sum(khatrirao(Factor_B,'r'),2);
Tensor_B=tensor(Data_B,Dimension_B);



end
